//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameStore.WebUI.PaymentService {
    using System.Runtime.Serialization;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PaymentStatus", Namespace="http://schemas.datacontract.org/2004/07/GameStore.Infrastructure.PaymentService.M" +
        "odels")]
    public enum PaymentStatus : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SuccessfulPayment = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NotEnoughMoney = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CardDoesNotExist = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PaymentFailed = 3,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PaymentService.IPaymentService")]
    public interface IPaymentService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPaymentService/PayUsingVisa", ReplyAction="http://tempuri.org/IPaymentService/PayUsingVisaResponse")]
        GameStore.WebUI.PaymentService.PaymentStatus PayUsingVisa(string cardNumber, string fullName, string cvvCode, int expirationMonth, int expirationYear, string purpose, decimal amountOfPayment, string email, string phoneNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPaymentService/PayUsingVisa", ReplyAction="http://tempuri.org/IPaymentService/PayUsingVisaResponse")]
        System.Threading.Tasks.Task<GameStore.WebUI.PaymentService.PaymentStatus> PayUsingVisaAsync(string cardNumber, string fullName, string cvvCode, int expirationMonth, int expirationYear, string purpose, decimal amountOfPayment, string email, string phoneNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPaymentService/PayUsingMasterCard", ReplyAction="http://tempuri.org/IPaymentService/PayUsingMasterCardResponse")]
        GameStore.WebUI.PaymentService.PaymentStatus PayUsingMasterCard(string cardNumber, string fullName, string cvvCode, int expirationMonth, int expirationYear, string purpose, decimal amountOfPayment, string email, string phoneNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPaymentService/PayUsingMasterCard", ReplyAction="http://tempuri.org/IPaymentService/PayUsingMasterCardResponse")]
        System.Threading.Tasks.Task<GameStore.WebUI.PaymentService.PaymentStatus> PayUsingMasterCardAsync(string cardNumber, string fullName, string cvvCode, int expirationMonth, int expirationYear, string purpose, decimal amountOfPayment, string email, string phoneNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPaymentService/IsUserExists", ReplyAction="http://tempuri.org/IPaymentService/IsUserExistsResponse")]
        bool IsUserExists(string cardNumber, string fullName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPaymentService/IsUserExists", ReplyAction="http://tempuri.org/IPaymentService/IsUserExistsResponse")]
        System.Threading.Tasks.Task<bool> IsUserExistsAsync(string cardNumber, string fullName);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPaymentServiceChannel : GameStore.WebUI.PaymentService.IPaymentService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PaymentServiceClient : System.ServiceModel.ClientBase<GameStore.WebUI.PaymentService.IPaymentService>, GameStore.WebUI.PaymentService.IPaymentService {
        
        public PaymentServiceClient() {
        }
        
        public PaymentServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PaymentServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PaymentServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PaymentServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public GameStore.WebUI.PaymentService.PaymentStatus PayUsingVisa(string cardNumber, string fullName, string cvvCode, int expirationMonth, int expirationYear, string purpose, decimal amountOfPayment, string email, string phoneNumber) {
            return base.Channel.PayUsingVisa(cardNumber, fullName, cvvCode, expirationMonth, expirationYear, purpose, amountOfPayment, email, phoneNumber);
        }
        
        public System.Threading.Tasks.Task<GameStore.WebUI.PaymentService.PaymentStatus> PayUsingVisaAsync(string cardNumber, string fullName, string cvvCode, int expirationMonth, int expirationYear, string purpose, decimal amountOfPayment, string email, string phoneNumber) {
            return base.Channel.PayUsingVisaAsync(cardNumber, fullName, cvvCode, expirationMonth, expirationYear, purpose, amountOfPayment, email, phoneNumber);
        }
        
        public GameStore.WebUI.PaymentService.PaymentStatus PayUsingMasterCard(string cardNumber, string fullName, string cvvCode, int expirationMonth, int expirationYear, string purpose, decimal amountOfPayment, string email, string phoneNumber) {
            return base.Channel.PayUsingMasterCard(cardNumber, fullName, cvvCode, expirationMonth, expirationYear, purpose, amountOfPayment, email, phoneNumber);
        }
        
        public System.Threading.Tasks.Task<GameStore.WebUI.PaymentService.PaymentStatus> PayUsingMasterCardAsync(string cardNumber, string fullName, string cvvCode, int expirationMonth, int expirationYear, string purpose, decimal amountOfPayment, string email, string phoneNumber) {
            return base.Channel.PayUsingMasterCardAsync(cardNumber, fullName, cvvCode, expirationMonth, expirationYear, purpose, amountOfPayment, email, phoneNumber);
        }
        
        public bool IsUserExists(string cardNumber, string fullName) {
            return base.Channel.IsUserExists(cardNumber, fullName);
        }
        
        public System.Threading.Tasks.Task<bool> IsUserExistsAsync(string cardNumber, string fullName) {
            return base.Channel.IsUserExistsAsync(cardNumber, fullName);
        }
    }
}
