// <auto-generated />
namespace GameStore.Infrastructure.EFDataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class DeletedSalt : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DeletedSalt));
        
        string IMigrationMetadata.Id
        {
            get { return "201612161321063_DeletedSalt"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
