//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GameStore.WebUI.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Подтвердить.
        /// </summary>
        public static string Accept {
            get {
                return ResourceManager.GetString("Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Аккаунт не найден.
        /// </summary>
        public static string AccountNotFound {
            get {
                return ResourceManager.GetString("AccountNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дата добавления.
        /// </summary>
        public static string AddingDate {
            get {
                return ResourceManager.GetString("AddingDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Все.
        /// </summary>
        public static string AllItems {
            get {
                return ResourceManager.GetString("AllItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Все время.
        /// </summary>
        public static string AllTime {
            get {
                return ResourceManager.GetString("AllTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ответ.
        /// </summary>
        public static string Answer {
            get {
                return ResourceManager.GetString("Answer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Забанить.
        /// </summary>
        public static string Ban {
            get {
                return ResourceManager.GetString("Ban", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Бан пользователю.
        /// </summary>
        public static string BanForUser {
            get {
                return ResourceManager.GetString("BanForUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Банк.
        /// </summary>
        public static string Bank {
            get {
                return ResourceManager.GetString("Bank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы не можете комментировать игру, так как были забанены до.
        /// </summary>
        public static string BanMessage {
            get {
                return ResourceManager.GetString("BanMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ограниченный до.
        /// </summary>
        public static string BannedTo {
            get {
                return ResourceManager.GetString("BannedTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Корзина.
        /// </summary>
        public static string Basket {
            get {
                return ResourceManager.GetString("Basket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Корзина пуста.
        /// </summary>
        public static string BasketIsEmpty {
            get {
                return ResourceManager.GetString("BasketIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Содержание.
        /// </summary>
        public static string Body {
            get {
                return ResourceManager.GetString("Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Купить.
        /// </summary>
        public static string Buy {
            get {
                return ResourceManager.GetString("Buy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на По возрастанию цены.
        /// </summary>
        public static string ByPriceAsc {
            get {
                return ResourceManager.GetString("ByPriceAsc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на По убыванию цены.
        /// </summary>
        public static string ByPriceDesc {
            get {
                return ResourceManager.GetString("ByPriceDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ПЕРЕЗВОНИТЬ МНЕ.
        /// </summary>
        public static string CallMeBack {
            get {
                return ResourceManager.GetString("CallMeBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отменить.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Счет не существует.
        /// </summary>
        public static string CardNotFound {
            get {
                return ResourceManager.GetString("CardNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Номер карты.
        /// </summary>
        public static string CardNumber {
            get {
                return ResourceManager.GetString("CardNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Номер карты должен содержать 16 цифр.
        /// </summary>
        public static string CardNumberMustContain16Digits {
            get {
                return ResourceManager.GetString("CardNumberMustContain16Digits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Имя владельца карты.
        /// </summary>
        public static string CartHoldersName {
            get {
                return ResourceManager.GetString("CartHoldersName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выбрать.
        /// </summary>
        public static string Choose {
            get {
                return ResourceManager.GetString("Choose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выберите язык.
        /// </summary>
        public static string ChooseLang {
            get {
                return ResourceManager.GetString("ChooseLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Код.
        /// </summary>
        public static string Code {
            get {
                return ResourceManager.GetString("Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Код должен содержать 4 буквы или цифры.
        /// </summary>
        public static string CodeContains4Symbols {
            get {
                return ResourceManager.GetString("CodeContains4Symbols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Комментарии.
        /// </summary>
        public static string Comments {
            get {
                return ResourceManager.GetString("Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Комментарии для игры.
        /// </summary>
        public static string CommentsForGame {
            get {
                return ResourceManager.GetString("CommentsForGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Комментарий был удален.
        /// </summary>
        public static string CommentWasDeleted {
            get {
                return ResourceManager.GetString("CommentWasDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Имя компании.
        /// </summary>
        public static string CompanyName {
            get {
                return ResourceManager.GetString("CompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Подтвердить.
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Подтверждение.
        /// </summary>
        public static string Confirmation {
            get {
                return ResourceManager.GetString("Confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Тип подтверждения.
        /// </summary>
        public static string ConfirmationType {
            get {
                return ResourceManager.GetString("ConfirmationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Подтвердить пароль.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Контактный номер.
        /// </summary>
        public static string ContactNumber {
            get {
                return ResourceManager.GetString("ContactNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Содержится английский перевод.
        /// </summary>
        public static string ContainEnglishTranslation {
            get {
                return ResourceManager.GetString("ContainEnglishTranslation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Создать.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Идентификатор клиента.
        /// </summary>
        public static string CustomerIdentifier {
            get {
                return ResourceManager.GetString("CustomerIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cvv2 содержит 2 или 3 цифры.
        /// </summary>
        public static string Cvv2Contains2Or3Digits {
            get {
                return ResourceManager.GetString("Cvv2Contains2Or3Digits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дата &quot;От&quot; должна быть раньше чем дата &quot;До&quot;.
        /// </summary>
        public static string DateFromMustBeEarlierThenDateTo {
            get {
                return ResourceManager.GetString("DateFromMustBeEarlierThenDateTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Интервал времени.
        /// </summary>
        public static string DateRange {
            get {
                return ResourceManager.GetString("DateRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на По умолчанию.
        /// </summary>
        public static string Default {
            get {
                return ResourceManager.GetString("Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Удалить.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Удаление.
        /// </summary>
        public static string Deleting {
            get {
                return ResourceManager.GetString("Deleting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Удаление игры.
        /// </summary>
        public static string DeletingGame {
            get {
                return ResourceManager.GetString("DeletingGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Удаление жанра.
        /// </summary>
        public static string DeletingGenre {
            get {
                return ResourceManager.GetString("DeletingGenre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Удаление типа платформы.
        /// </summary>
        public static string DeletingPlatformType {
            get {
                return ResourceManager.GetString("DeletingPlatformType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Удаление издателя.
        /// </summary>
        public static string DeletingPublisher {
            get {
                return ResourceManager.GetString("DeletingPublisher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на При удалении жанра будут удалены указанные поджанры и все их потомки.
        /// </summary>
        public static string DeletingSubGenresMessage {
            get {
                return ResourceManager.GetString("DeletingSubGenresMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Удаление пользователя.
        /// </summary>
        public static string DeletingUser {
            get {
                return ResourceManager.GetString("DeletingUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы уверены, что хотите удалить пользователя с именем.
        /// </summary>
        public static string DeletingUserMessage {
            get {
                return ResourceManager.GetString("DeletingUserMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Доставить.
        /// </summary>
        public static string Deliver {
            get {
                return ResourceManager.GetString("Deliver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Описание.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Детали.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Снято с производства.
        /// </summary>
        public static string Discounted {
            get {
                return ResourceManager.GetString("Discounted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Скачать.
        /// </summary>
        public static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Редактировать.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Адрес электронной почты.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Адрес электронной почты - обязательный.
        /// </summary>
        public static string EmailRequired {
            get {
                return ResourceManager.GetString("EmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Английское описание.
        /// </summary>
        public static string EnglishDescription {
            get {
                return ResourceManager.GetString("EnglishDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Английское описание - обязательно для ввода.
        /// </summary>
        public static string EnglishDescriptionIsRequired {
            get {
                return ResourceManager.GetString("EnglishDescriptionIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Английское имя - обязательно для ввода.
        /// </summary>
        public static string EnglishNameIsRequired {
            get {
                return ResourceManager.GetString("EnglishNameIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вход.
        /// </summary>
        public static string Entrance {
            get {
                return ResourceManager.GetString("Entrance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Случилась ошибка, пожалуйста, попытайтесь зайти позже.
        /// </summary>
        public static string ErrorOccured {
            get {
                return ResourceManager.GetString("ErrorOccured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Некорректный формат даты. Пример: 06/17.
        /// </summary>
        public static string ExampleExpireDate {
            get {
                return ResourceManager.GetString("ExampleExpireDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Срок годности.
        /// </summary>
        public static string ExpiryDate {
            get {
                return ResourceManager.GetString("ExpiryDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 50 единиц.
        /// </summary>
        public static string FiftyItems {
            get {
                return ResourceManager.GetString("FiftyItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отфильтровать.
        /// </summary>
        public static string Filter {
            get {
                return ResourceManager.GetString("Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Запрещено.
        /// </summary>
        public static string Forbidden {
            get {
                return ResourceManager.GetString("Forbidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы не имеете доступа к данной странице.
        /// </summary>
        public static string ForbiddenMessage {
            get {
                return ResourceManager.GetString("ForbiddenMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на От.
        /// </summary>
        public static string From {
            get {
                return ResourceManager.GetString("From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пример: &quot;Имя Фамилия&quot;.
        /// </summary>
        public static string FullNameExample {
            get {
                return ResourceManager.GetString("FullNameExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Создание игры.
        /// </summary>
        public static string GameCreating {
            get {
                return ResourceManager.GetString("GameCreating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Игра должна содержать хотся бы один тип платформы.
        /// </summary>
        public static string GameMustContainAtLeastOnePlatformType {
            get {
                return ResourceManager.GetString("GameMustContainAtLeastOnePlatformType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Игры.
        /// </summary>
        public static string Games {
            get {
                return ResourceManager.GetString("Games", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Игр не достаточно для заказа .
        /// </summary>
        public static string GamesNotEnoughForOrderMaking {
            get {
                return ResourceManager.GetString("GamesNotEnoughForOrderMaking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Игр на странице.
        /// </summary>
        public static string GamesOnPage {
            get {
                return ResourceManager.GetString("GamesOnPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Жанры.
        /// </summary>
        public static string Genres {
            get {
                return ResourceManager.GetString("Genres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Скрыть.
        /// </summary>
        public static string Hide {
            get {
                return ResourceManager.GetString("Hide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на История.
        /// </summary>
        public static string History {
            get {
                return ResourceManager.GetString("History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Домашняя страница.
        /// </summary>
        public static string HomePage {
            get {
                return ResourceManager.GetString("HomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на IBox.
        /// </summary>
        public static string IBox {
            get {
                return ResourceManager.GetString("IBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Идентификатор.
        /// </summary>
        public static string Identifier {
            get {
                return ResourceManager.GetString("Identifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Некорректный адрес электронной почты.
        /// </summary>
        public static string IncorrectEmail {
            get {
                return ResourceManager.GetString("IncorrectEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Некорректный адрес электронной почты.
        /// </summary>
        public static string InvalidEmail {
            get {
                return ResourceManager.GetString("InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пароль должне содержать цифры или буквы и быть длинной от 6 до 30 символов.
        /// </summary>
        public static string InvalidPassword {
            get {
                return ResourceManager.GetString("InvalidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ключ.
        /// </summary>
        public static string Key {
            get {
                return ResourceManager.GetString("Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Последний месяц.
        /// </summary>
        public static string LastMonth {
            get {
                return ResourceManager.GetString("LastMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Последняя неделя.
        /// </summary>
        public static string LastWeek {
            get {
                return ResourceManager.GetString("LastWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Последний год.
        /// </summary>
        public static string LastYear {
            get {
                return ResourceManager.GetString("LastYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Загрузить асинхронно.
        /// </summary>
        public static string LoadAsynchronously {
            get {
                return ResourceManager.GetString("LoadAsynchronously", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Загрузить асинхронно Http.
        /// </summary>
        public static string LoadHttpAsynchronously {
            get {
                return ResourceManager.GetString("LoadHttpAsynchronously", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Загрузить синхронно.
        /// </summary>
        public static string LoadSynchronously {
            get {
                return ResourceManager.GetString("LoadSynchronously", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Войти.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выйти.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сделать заказ.
        /// </summary>
        public static string MakeOrder {
            get {
                return ResourceManager.GetString("MakeOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Управление учетной записью.
        /// </summary>
        public static string ManagingAccount {
            get {
                return ResourceManager.GetString("ManagingAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Макс..
        /// </summary>
        public static string Max {
            get {
                return ResourceManager.GetString("Max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Максимальаня длина комментария: 200.
        /// </summary>
        public static string MaxCommentBodyLength200 {
            get {
                return ResourceManager.GetString("MaxCommentBodyLength200", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Максимальная длина имени комментатора: 50.
        /// </summary>
        public static string MaxCommentNameLength50 {
            get {
                return ResourceManager.GetString("MaxCommentNameLength50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Максимальная длина описания: 500.
        /// </summary>
        public static string MaxDescriptionLength500 {
            get {
                return ResourceManager.GetString("MaxDescriptionLength500", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Максимальная длина имени игры: 100.
        /// </summary>
        public static string MaxGameNameLength100 {
            get {
                return ResourceManager.GetString("MaxGameNameLength100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Максимальная длина ключа: 30.
        /// </summary>
        public static string MaxKeyLength30 {
            get {
                return ResourceManager.GetString("MaxKeyLength30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Максимальная длина имени: 70.
        /// </summary>
        public static string MaxNameLenght70 {
            get {
                return ResourceManager.GetString("MaxNameLenght70", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Максимальная длина имени типа платформы - 50.
        /// </summary>
        public static string MaxPlatformTypeLength50 {
            get {
                return ResourceManager.GetString("MaxPlatformTypeLength50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Мин..
        /// </summary>
        public static string Min {
            get {
                return ResourceManager.GetString("Min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Минимальная длина имени игры: 3.
        /// </summary>
        public static string MinGameNameLength3 {
            get {
                return ResourceManager.GetString("MinGameNameLength3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Мнимальная цена должна быть меньше чем максимальная.
        /// </summary>
        public static string MinPriceMustBeLessThenMax {
            get {
                return ResourceManager.GetString("MinPriceMustBeLessThenMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Найболее комментируемые.
        /// </summary>
        public static string MostCommended {
            get {
                return ResourceManager.GetString("MostCommended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Найболее популярные.
        /// </summary>
        public static string MostPopular {
            get {
                return ResourceManager.GetString("MostPopular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Имя.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Новый.
        /// </summary>
        public static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Новый комментарий.
        /// </summary>
        public static string NewComment {
            get {
                return ResourceManager.GetString("NewComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Нет.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не достаточно денег на счету.
        /// </summary>
        public static string NotEnoughMoney {
            get {
                return ResourceManager.GetString("NotEnoughMoney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пароль и потверждение не совпадают.
        /// </summary>
        public static string NotEqualPasswords {
            get {
                return ResourceManager.GetString("NotEqualPasswords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не оплачено.
        /// </summary>
        public static string NotPaid {
            get {
                return ResourceManager.GetString("NotPaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 100 единиц.
        /// </summary>
        public static string OneHundredItems {
            get {
                return ResourceManager.GetString("OneHundredItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Заказ.
        /// </summary>
        public static string Order {
            get {
                return ResourceManager.GetString("Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дата заказа.
        /// </summary>
        public static string OrderDate {
            get {
                return ResourceManager.GetString("OrderDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Заказ оплачен.
        /// </summary>
        public static string OrderPaid {
            get {
                return ResourceManager.GetString("OrderPaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Заказы.
        /// </summary>
        public static string Orders {
            get {
                return ResourceManager.GetString("Orders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Заказ доставлен.
        /// </summary>
        public static string OrderShipped {
            get {
                return ResourceManager.GetString("OrderShipped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Статус заказа.
        /// </summary>
        public static string OrderStatus {
            get {
                return ResourceManager.GetString("OrderStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Страница не найдена.
        /// </summary>
        public static string PageNotFound {
            get {
                return ResourceManager.GetString("PageNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Оплачено.
        /// </summary>
        public static string Paid {
            get {
                return ResourceManager.GetString("Paid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Родительский жанр.
        /// </summary>
        public static string ParentGenre {
            get {
                return ResourceManager.GetString("ParentGenre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пароль.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Оплатить.
        /// </summary>
        public static string Pay {
            get {
                return ResourceManager.GetString("Pay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дата покупки.
        /// </summary>
        public static string PayingDate {
            get {
                return ResourceManager.GetString("PayingDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Оплата.
        /// </summary>
        public static string Payment {
            get {
                return ResourceManager.GetString("Payment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Оплата не выполнена.
        /// </summary>
        public static string PaymentFailed {
            get {
                return ResourceManager.GetString("PaymentFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Результат оплаты.
        /// </summary>
        public static string PaymentResult {
            get {
                return ResourceManager.GetString("PaymentResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Оплатить используя накладной файл.
        /// </summary>
        public static string PayUsingInvoiceFile {
            get {
                return ResourceManager.GetString("PayUsingInvoiceFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Оплатить используя банковский сайт.
        /// </summary>
        public static string PayViaBankSite {
            get {
                return ResourceManager.GetString("PayViaBankSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Оплатить используя терминал IBox.
        /// </summary>
        public static string PayViaIBoxTerminal {
            get {
                return ResourceManager.GetString("PayViaIBoxTerminal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Номер мобильного телефона.
        /// </summary>
        public static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пример: &quot;+380501234567&quot;.
        /// </summary>
        public static string PhoneNumberExample {
            get {
                return ResourceManager.GetString("PhoneNumberExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Номер мобильного телефона - обязательный.
        /// </summary>
        public static string PhoneNumberRequired {
            get {
                return ResourceManager.GetString("PhoneNumberRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Типы платформ.
        /// </summary>
        public static string PlatformTypes {
            get {
                return ResourceManager.GetString("PlatformTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Цена.
        /// </summary>
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Интервал цены.
        /// </summary>
        public static string PriceRange {
            get {
                return ResourceManager.GetString("PriceRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Опубликовано за.
        /// </summary>
        public static string PublishedFor {
            get {
                return ResourceManager.GetString("PublishedFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Издатель.
        /// </summary>
        public static string Publisher {
            get {
                return ResourceManager.GetString("Publisher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавление издателя.
        /// </summary>
        public static string PublisherCreating {
            get {
                return ResourceManager.GetString("PublisherCreating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Издатели.
        /// </summary>
        public static string Publishers {
            get {
                return ResourceManager.GetString("Publishers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дата публикации.
        /// </summary>
        public static string PublishingDate {
            get {
                return ResourceManager.GetString("PublishingDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Количество.
        /// </summary>
        public static string Quantity {
            get {
                return ResourceManager.GetString("Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Цитата.
        /// </summary>
        public static string Quote {
            get {
                return ResourceManager.GetString("Quote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Зарегистрировать.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Регистрация.
        /// </summary>
        public static string Registration {
            get {
                return ResourceManager.GetString("Registration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Удалить.
        /// </summary>
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ответ для.
        /// </summary>
        public static string RepliedTo {
            get {
                return ResourceManager.GetString("RepliedTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Роли.
        /// </summary>
        public static string Roles {
            get {
                return ResourceManager.GetString("Roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сохранить.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сохранить заказ.
        /// </summary>
        public static string SaveOrder {
            get {
                return ResourceManager.GetString("SaveOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поиск по имени.
        /// </summary>
        public static string SearchByName {
            get {
                return ResourceManager.GetString("SearchByName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выберите изображение для загрузки.
        /// </summary>
        public static string SelectImageToLoad {
            get {
                return ResourceManager.GetString("SelectImageToLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отправить.
        /// </summary>
        public static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дата доставки.
        /// </summary>
        public static string ShippedDate {
            get {
                return ResourceManager.GetString("ShippedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Показать.
        /// </summary>
        public static string Show {
            get {
                return ResourceManager.GetString("Show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сортировка.
        /// </summary>
        public static string Sorting {
            get {
                return ResourceManager.GetString("Sorting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поджанры.
        /// </summary>
        public static string Subgenres {
            get {
                return ResourceManager.GetString("Subgenres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отправить.
        /// </summary>
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 10 единиц.
        /// </summary>
        public static string TenItems {
            get {
                return ResourceManager.GetString("TenItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Три года.
        /// </summary>
        public static string ThreeYears {
            get {
                return ResourceManager.GetString("ThreeYears", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на До.
        /// </summary>
        public static string To {
            get {
                return ResourceManager.GetString("To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на К корзине.
        /// </summary>
        public static string ToBasket {
            get {
                return ResourceManager.GetString("ToBasket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на К странице с комментариями.
        /// </summary>
        public static string ToCommentsPage {
            get {
                return ResourceManager.GetString("ToCommentsPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на На главную.
        /// </summary>
        public static string ToHomePage {
            get {
                return ResourceManager.GetString("ToHomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Игр на сайте.
        /// </summary>
        public static string TotalAmountOfGameForSite {
            get {
                return ResourceManager.GetString("TotalAmountOfGameForSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Итого.
        /// </summary>
        public static string TotalPrice {
            get {
                return ResourceManager.GetString("TotalPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 20 единиц.
        /// </summary>
        public static string TwentyItems {
            get {
                return ResourceManager.GetString("TwentyItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Два года.
        /// </summary>
        public static string TwoYears {
            get {
                return ResourceManager.GetString("TwoYears", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Количество в запасе.
        /// </summary>
        public static string UnitsInStock {
            get {
                return ResourceManager.GetString("UnitsInStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Неизвестный.
        /// </summary>
        public static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Обновить.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Обновление.
        /// </summary>
        public static string Updating {
            get {
                return ResourceManager.GetString("Updating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Обновление пользователя.
        /// </summary>
        public static string UpdatingUser {
            get {
                return ResourceManager.GetString("UpdatingUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пользователи.
        /// </summary>
        public static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Количество просмотров.
        /// </summary>
        public static string ViewsCount {
            get {
                return ResourceManager.GetString("ViewsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Visa.
        /// </summary>
        public static string Visa {
            get {
                return ResourceManager.GetString("Visa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Да.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Срок годности карты истек.
        /// </summary>
        public static string YourCreditCardExpirationDateIsInThePast {
            get {
                return ResourceManager.GetString("YourCreditCardExpirationDateIsInThePast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ваше имя.
        /// </summary>
        public static string YourName {
            get {
                return ResourceManager.GetString("YourName", resourceCulture);
            }
        }
    }
}
